SubscriptionPortal/Controllers/EmpController.cs
using SubscriptionPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SubscriptionPortal.Controllers
{
    public class EmpController : Controller
    {
        private readonly SubscriptionPortalContext _context;

        public EmpController(SubscriptionPortalContext context)
        {
            _context = context;
        }

        // GET: Employee
        public async Task<IActionResult> Index(string currentFilter,string searchString, int? pageNumber)
        {
            //return View(await _context.Subscriptions.ToListAsync());

            //return View(await _context.Employee.ToListAsync());

            //return View(await _context.Employee.ToListAsync());

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var emps = from e in _context.Employee
                       select e;

            if (!String.IsNullOrEmpty(searchString))
                emps = emps.Where(e => e.Name.Contains(searchString));

            int pageSize = 5;            
            //return View(await PaginatedList<Emp>.Create(emps, pageNumber ?? 1, pageSize));
         //   return View(await PaginatedList<Emp>.CreateAsync(emps, pageNumber ?? 1, pageSize));
            //int pageSize = 5;
            return View(await PaginatedList<Emp>.CreateAsync(emps, pageNumber ?? 1, pageSize));

        }

        //GET : Employee/ create
        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new Emp());
            else
                return View(_context.Employee.Find(id));
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("EmpId,Name,EmailId,Department,Location")] Emp emp)
        {
            if (ModelState.IsValid)
            {
                if (emp.EmpId == 0)
                    _context.Add(emp);
                else
                    _context.Update(emp);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(emp);
        }

        // GET: Employee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var emp = await _context.Employee.FindAsync(id);
            _context.Employee.Remove(emp);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

SubscriptionPortal/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Management.Automation;
using System.Management.Automation.Runspaces;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.PowerShell;
using SubscriptionPortal.Models;

namespace SubscriptionPortal.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly SubscriptionPortalContext _context;
        //public string ApplicationName { get; set; }
        public SubscriptionController(SubscriptionPortalContext context)
        {
            _context = context;
        }

        // GET: Subscription
        public async Task<IActionResult> Index()
        {
            List<SelectListItem> ApplicationNames = new List<SelectListItem>
            {
                new SelectListItem { Value = "SelectApplication", Text = "Select Application" },
                new SelectListItem { Value = "GiftRegister", Text = "Gift Register" },
                new SelectListItem { Value = "MeetingExpanse", Text = "Meeting Expanse" },
                new SelectListItem { Value = "ManPower", Text = "Man Power" },
                new SelectListItem { Value = "NewHire", Text = "New Hire"},
            };

            //assigning SelectListItem to view Bag
            ViewBag.ApplicationName = ApplicationNames;

            var subscription = from m in _context.Subscription
                               select m;

            if (!String.IsNullOrEmpty(HttpContext.Session.GetString("userid")))
            {
                subscription = subscription.Where(s => s.Userid.Contains(HttpContext.Session.GetString("userid")));
            }

            return View(await subscription.ToListAsync());

            // return View(await _context.Subscription.ToListAsync());
            //List<Subscription> subscription = new List<Subscription>();
            //subscription = await _context.Subscription.AsNoTracking()
            //    .Include(m => m.Userid == HttpContext.Session.GetString("userid"))
            //    //.Include(x => x.Region)
            //    .ToListAsync();

            //return View(await _context.Subscription.FirstOrDefaultAsync(m => m.Userid == HttpContext.Session.GetString("userid")));
            ////var  subscription = await _context.Subscription
            ////    .FirstOrDefaultAsync(m => m.Userid == HttpContext.Session.GetString("userid"));

            ////if (subscription == null)
            ////{
            ////    return View(await subscription.ToListAsync());
            ////}

            ////return View(subscription);

        }
        // GET: Subscription/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subscription = await _context.Subscription
                .FirstOrDefaultAsync(m => m.SubscriptionId == id || m.Userid == HttpContext.Session.GetString("userid") );
            if (subscription == null)
            {
                return NotFound();
            }

            return View(subscription);
        }

        // GET: Subscription/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subscription/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubscriptionId,ApplicationName,CompanyName,DBName,DBUserId,DBUserPassword,EmailId,Location,Userid")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                subscription.RequestStatus = "Pending";
                subscription.Userid = ViewBag.userid;
                subscription.Userid = TempData["Userid"].ToString();
                subscription.Userid = HttpContext.Session.GetString("userid");

                _context.Add(subscription);
                await _context.SaveChangesAsync();

                ////Thread.Sleep(5000);

                //string containername = "mysqldb" + subscription.CompanyName.Trim();
                //string podname = "mysqldb" + subscription.CompanyName.Trim();
                //string dbname = "mysqldb" + subscription.CompanyName.Trim();
                //string dbusername = "dbusername";
                //string dbpassword = "dbusername";
                //string rootuser = "root";
                //string rootpassword = "dbpassword";

               // string appname = subscription.ApplicationName.Trim().ToString().ToLower().Replace(' ', '-') + '-' + subscription.CompanyName.Trim();

               // List<object> output =  RunPowershellScript(containername, podname, dbname, dbusername, dbpassword, rootuser, rootpassword, appname);
              //  ViewBag.error = output[0];
               // ViewBag.results = output[1];
              return RedirectToAction(nameof(Index));
            }
            
            return View(subscription);
        }
        public List<object> RunPowershellScript(string containername, string podname, string dbname, string dbusername, string dbpassword, string rootuser, string rootpassword, string appname)
        {
            string fullPath = Path.GetFullPath("Files/0.mysqlscript.ps1");
            //string fileName = Path.GetFileName("Files/0.mysqlscript.ps1");

            //using (RunspaceInvoke invoker = new RunspaceInvoke())
            //{
            //    invoker.Invoke("Set-ExecutionPolicy Unrestricted");
            //}

            //StringBuilder OSScript = new StringBuilder("Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted;");
            //OSScript.Append(@"other really exciting stuff");

            string cmdArg = fullPath;
            Runspace runspace = RunspaceFactory.CreateRunspace();
            //runspace.ApartmentState = System.Threading.ApartmentState.STA;
            runspace.ThreadOptions = PSThreadOptions.UseCurrentThread;

            runspace.Open();

            Pipeline pipeline = runspace.CreatePipeline();
            //pipeline.Commands.Add("Set-ExecutionPolicy");

            Command command = new Command(cmdArg);

            CommandParameter usernameParm = new CommandParameter("username", "mujoshi1");
            command.Parameters.Add(usernameParm);
            CommandParameter userpasswordParm = new CommandParameter("userpassword", "Welcome@IBM9535084436s");
            command.Parameters.Add(userpasswordParm);
            CommandParameter serverlinkParm = new CommandParameter("serverlink", "https://api.sandbox.x8i5.p1.openshiftapps.com:6443");
            command.Parameters.Add(serverlinkParm);
            CommandParameter servertokenParm = new CommandParameter("servertoken", "sha256~dCDKlZ5DVXxVub8nYlQGTn3pX5cLFHnDOWNXph7mmIo");
            command.Parameters.Add(servertokenParm);
            CommandParameter containernameParm = new CommandParameter("containername", containername);
            command.Parameters.Add(containernameParm);
            CommandParameter podnameParm = new CommandParameter("podname", podname);
            command.Parameters.Add(podnameParm);
            CommandParameter dbnameParm = new CommandParameter("dbname", dbname);
            command.Parameters.Add(dbnameParm);
            CommandParameter dbusernameParm = new CommandParameter("dbusername", dbusername);
            command.Parameters.Add(dbusernameParm);
            CommandParameter dbpasswordParm = new CommandParameter("dbpassword", dbpassword);
            command.Parameters.Add(dbpasswordParm);
            CommandParameter rootuserParm = new CommandParameter("rootuser", rootuser);
            command.Parameters.Add(rootuserParm);
            CommandParameter rootpasswordParm = new CommandParameter("rootpassword", rootpassword);
            command.Parameters.Add(rootpasswordParm);
            CommandParameter envnameParm = new CommandParameter("envname", "Development");
            command.Parameters.Add(envnameParm);
            CommandParameter appnameParm = new CommandParameter("appname", appname);
            command.Parameters.Add(appnameParm);

            pipeline.Commands.Add(command);
            //pipeline.Commands.AddScript(cmdArg);

            pipeline.Commands[0].MergeMyResults(PipelineResultTypes.Error, PipelineResultTypes.Output);
            Collection<PSObject> results = pipeline.Invoke("Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned");
            var error = pipeline.Error.ReadToEnd();
            runspace.Close();

            if (error.Count >= 1)
            {
                string errors = "";
                foreach (var Error in error)
                {
                    errors = errors + " " + Error.ToString();
                }
            }
            if (results != null)
            {
            }


            ////Execute PS1(PowerShell script) file
            //using (PowerShell PowerShellInst = PowerShell.Create())
            //{
            //    //string path = Path.GetFullPath("~/0.mysqlscript.ps1");
            //    //string path = System.IO.Path.GetDirectoryName(@"C:\Temp\") + "\\Get-EventLog.ps1";
            //   // path = System.IO.Path.GetDirectoryName(@"C:\Temp\") + "\\0.mysqlscript.ps1";
            //    if (!string.IsNullOrEmpty(fullPath))
            //    {
            //        PowerShellInst.AddScript(System.IO.File.ReadAllText(fullPath));
            //        PowerShellInst.AddParameter("username", "mujoshi1");
            //        PowerShellInst.AddParameter("userpassword", "Welcome@IBM9535084436s");

SubscriptionPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Subscription Portal</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css" asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position" asp-fallback-test-value="absolute" crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #87cefa;
        }

        #login .container #login-row #login-column #login-box {
            margin-top: 120px;
            max-width: 400px;
            height: 350px;
            border: 1px solid #9C9C9C;
            background-color: #EAEAEA;
        }

            #login .container #login-row #login-column #login-box #login-form {
                padding: 20px;
            }

                #login .container #login-row #login-column #login-box #login-form #register-link {
                    margin-top: -85px;
                }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Subscription Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">Employee Information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="Index">Subscription</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - @ViewData["Title"] SubscriptionPortal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SubscriptionPortal/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Subscription Portal</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.css" asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position" asp-fallback-test-value="absolute" crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #87cefa;
        }

        #login .container #login-row #login-column #login-box {
            margin-top: 120px;
            max-width: 400px;
            height: 350px;
            border: 1px solid #9C9C9C;
            background-color: #EAEAEA;
        }

            #login .container #login-row #login-column #login-box #login-form {
                padding: 20px;
            }

                #login .container #login-row #login-column #login-box #login-form #register-link {
                    margin-top: -85px;
                }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div>Welcome to Subscription Portal</div>
                    @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Subscription Portal</a>*@
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">Employee Information</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Subscription" asp-action="Index">Subscription</a>
                    </li>*@

                        </ul>
                    </div>
                </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - @ViewData["Title"] Subscription Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>